<?xml version="1.0"?>
<package format="3">
  <name>ardupilot_bt_navigator</name>
  <version>0.0.1</version>
  <description>Behavior tree navigator for Ardupilot.</description>
  <maintainer email="todo@example.com">TODO Maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>ardupilot_bt</depend>
  <depend>ardupilot_bt_nodes</depend>
  <depend>ardupilot_utils</depend>
  <depend>ardupilot_lifecycle_manager</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
